[features]
seeds = false
[programs.localnet]
mvp_contract = "YMC3YPso17ZRQNm5dAZw8vjWAdjexWoyKZs6E3pyA4B"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kapollo/.config/solana/id.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
